# Generated by Django 5.1.4 on 2024-12-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='gif',
            field=models.ImageField(blank=True, null=True, upload_to='animals_gifs/'),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
