# Generated by Django 5.1.4 on 2024-12-22 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0005_remove_habitat_image_alter_animal_habitat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='image',
        ),
    ]
